# version: '3.3' # for CentOS7
version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sharifstarter
    networks:
      - network
    volumes:
      - psql-data:/var/lib/postgres/data
    restart: always
    ports:
      - 5432:5432
      
  backend:
    build: ./back
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - network
    depends_on:
      - db
      - backend

networks:
  network:
  
volumes:
  psql-data:

